import streamlit as st
from datetime import datetime

from auth.auth import check_login
from utils.navigation import show_sidebar

from ai.gemini import get_health_response

from database.database import (
    save_ai_history
)

from utils.helper import (
    footer,
    section_title
)

# ==========================================
# PROTECT PAGE
# ==========================================

if not check_login():
    st.switch_page("MediLink_AI.py")

# ==========================================
# SIDEBAR
# ==========================================

show_sidebar()

# ==========================================
# HERO SECTION
# ==========================================

st.markdown("""
<div class="hero">

<h1>🤖 AI Symptom Checker</h1>

<h3>Your AI Healthcare Assistant</h3>

<p style="font-size:18px;">

Describe your symptoms and receive educational
health guidance powered by Google Gemini AI.

</p>

</div>
""", unsafe_allow_html=True)

# ==========================================
# INTRODUCTION
# ==========================================

st.info(f"""
👋 **Welcome {st.session_state.full_name}!**

Please describe **all** your symptoms clearly.

The more details you provide, the better the educational guidance.

⚠️ **MediLink AI does NOT diagnose diseases or prescribe medications.**
""")

# ==========================================
# INPUT
# ==========================================

section_title("Describe Your Symptoms", "🩺")

symptoms = st.text_area(
    "",
    height=220,
    placeholder="""
Example:

• Fever for 3 days

• Headache

• Body pain

• Chills

• Vomiting

• Difficulty sleeping

• Age: 24

• Female
"""
)

st.caption(
    "💡 Tip: Include how long you've had the symptoms, your age, and any other important details."
)

st.write("")

# ==========================================
# ANALYZE
# ==========================================

if st.button(
    "🔍 Analyze Symptoms",
    use_container_width=True
):

    if symptoms.strip() == "":

        st.warning("⚠️ Please describe your symptoms first.")

    else:

        progress = st.progress(0)

        try:

            with st.spinner("🤖 MediLink AI is analyzing your symptoms..."):

                progress.progress(20)

                response = get_health_response(symptoms)

                progress.progress(70)

                save_ai_history(
                    st.session_state.user_id,
                    symptoms,
                    response
                )

                progress.progress(100)

            st.success("✅ Analysis Complete")

            st.divider()

            section_title("AI Health Guidance", "🩺")

            st.markdown(response)

            st.divider()

            # ==========================================
            # DOWNLOAD REPORT
            # ==========================================

            report = f"""
MediLink AI Health Report

Generated:
{datetime.now().strftime("%d %B %Y %I:%M %p")}

==================================================

Symptoms Reported

{symptoms}

==================================================

AI Health Guidance

{response}

==================================================

Medical Disclaimer

This report is provided for educational purposes only.

It is NOT a medical diagnosis.

Always consult a qualified healthcare professional.

Generated by MediLink AI.
"""

            st.download_button(
                "📄 Download My Health Report",
                data=report,
                file_name="MediLink_AI_Report.txt",
                mime="text/plain",
                use_container_width=True
            )

        except Exception as e:

            error = str(e)

            if "429" in error:

                st.warning("""
⚠️ MediLink AI has temporarily reached its AI request limit.

Please wait about one minute and try again.

This only affects the AI feature temporarily.
""")

            else:

                st.error("❌ Unable to contact Gemini AI.")

                with st.expander("Technical Details"):

                    st.code(error)

st.write("")

# ==========================================
# EMERGENCY WARNING
# ==========================================

section_title("Emergency Warning Signs", "🚨")

st.error("""
Seek immediate medical attention if you experience:

• Difficulty breathing

• Severe chest pain

• Loss of consciousness

• Heavy bleeding

• Seizures

• Stroke symptoms

• Severe allergic reactions

• Persistent high fever

• Confusion or inability to stay awake
""")

# ==========================================
# HEALTH TIPS
# ==========================================

section_title("Helpful Health Tips", "💡")

st.success("""
✔ Drink plenty of clean water.

✔ Get enough rest.

✔ Avoid self-medication.

✔ Visit a Primary Health Centre (PHC) or hospital if symptoms worsen.

✔ Follow treatment prescribed by qualified healthcare professionals.

✔ Eat balanced meals to support recovery.
""")

# ==========================================
# DISCLAIMER
# ==========================================

st.warning("""
### ⚠️ Medical Disclaimer

MediLink AI provides educational health information only.

It does **NOT** diagnose diseases.

It does **NOT** prescribe medications.

Always consult a qualified healthcare professional for proper diagnosis and treatment.

In an emergency, visit the nearest hospital immediately.
""")

# ==========================================
# FOOTER
# ==========================================

footer()